### ISSUE TITLE
lack of utils.py file imported in main.py

### ISSUE THREAD

**Issue by TravisCao** [ecada/SRDP_ADA#1]
Hi, I tried to run your program, but found there was no utils.py needed in main.py file.
```bash
File "/home/ubuntu/SRDP_ADA/main.py", line 18, in <module>
    from utils import utils
ModuleNotFoundError: No module named 'utils'
```

**Comment by ecada** [comment]
Hi! The utils folder can be found at https://github.com/Zhendong-Wang/Diffusion-Policies-for-Offline-RL
